/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ScannerMarks;
import java.util.*;


public class App {
    

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String showPass;
        String myMessage;


        // Get Student Information
        System.out.print("Enter Student Number: ");
        int studentNumber = scanner.nextInt();
        scanner.nextLine(); // consume the newline character

        System.out.print("Enter Student Name: ");
        String name = scanner.nextLine();

        System.out.print("Enter Surname: ");
        String surname = scanner.nextLine();


        System.out.print("Enter Email: ");
        String email = scanner.nextLine();


        System.out.print("Enter Phone Number: ");
        String phoneNumber = scanner.nextLine();

        // GET MARKS
        System.out.print("Enter Mark 1: ");
        double mark1 = scanner.nextDouble();

        System.out.print("Enter Mark 2: ");
        double mark2 = scanner.nextDouble();

        System.out.print("Enter Assignment Mark: ");
        double assignmentMark = scanner.nextDouble();


        System.out.print("Enter Exam 1: ");
        double examMark = scanner.nextDouble();

        //Calculate Final Mark
        double dpMark = CalculateDpMark(mark1,mark2,assignmentMark);

        // Calculate Final Mark
        double finalMark = CalculateFinalMark(dpMark,examMark);

        //Check If Passed
        if(finalMark >= 0 && finalMark <= 46){
            showPass = "Failed";
            myMessage = finalMark + " You Have " + showPass;
        }else if(finalMark >= 47 && finalMark <= 49){
            showPass = "Support";
            myMessage = finalMark + " You Have " + showPass;
        }else if(finalMark >= 50 && finalMark <= 74){
            showPass = "Passed";
            myMessage = finalMark + " You Have " + showPass;
        }else{
            showPass = "Distinction";
            myMessage = finalMark + " You Have " + showPass;
        }

        // Display student information and final mark
        System.out.println("\nStudent Information");
        System.out.println("Student Number: " + studentNumber);
        System.out.println("Name: " + name);
        System.out.println("Suranme: " + surname);
        System.out.println("Email: " + email);
        

        System.out.println("\nMarks: ");
        System.out.println("Mark 1: " + mark1);
        System.out.println("Mark 2: " + mark2);
        System.out.println("Assignment Mark: " + assignmentMark);
        System.out.println("Exam Mark: " + examMark);
        
        
        System.out.println("\nDully Perfomed Mark: " + dpMark);
        System.out.println("Final Mark: " + finalMark);

        System.out.println("DID PASS: "+ showPass);
        System.out.println("PASS GRADE: "+ myMessage);

        //close scanner

    }

    private static double CalculateDpMark(double mark1,double mark2,double assignmentMark){
        return (mark1 + mark2 + assignmentMark) / 3;
    }

    private static double CalculateFinalMark(double dpMark,double examMark){
        return (dpMark * 0.4 ) +  (examMark * 0.6);
    }
}
